import webbrowser
import pyautogui
import time
time.sleep(1)
webbrowser. open_new_tab("www.google.com")
time.sleep(3)
pyautogui.press("y")
pyautogui.press("o")
pyautogui.press("u")
pyautogui.press("r")
pyautogui.press(" ")
pyautogui.press("p")
pyautogui.press("c")
pyautogui.press(" ")
pyautogui.press("h")
pyautogui.press("a")
pyautogui.press("s")
pyautogui.press(" ")
pyautogui.press("b")
pyautogui.press("e")
pyautogui.press("e")
pyautogui.press("n")
pyautogui.press(" ")
pyautogui.press("h")
pyautogui.press("a")
pyautogui.press("c")
pyautogui.press("k")
pyautogui.press("e")
pyautogui.press("d")
pyautogui.press(" ")
pyautogui.press("p")
pyautogui.press("c")
pyautogui.press(" ")
pyautogui.press("w")
pyautogui.press("i")
pyautogui.press("l")
pyautogui.press("l")
pyautogui.press(" ")
pyautogui.press("u")
pyautogui.press("p")
pyautogui.press("d")
pyautogui.press("a")
pyautogui.press("t")
pyautogui.press("e")
pyautogui.press(" ")
pyautogui.press("t")
pyautogui.press("o")
pyautogui.press(" ")
pyautogui.press("c")
pyautogui.press("l")
pyautogui.press("e")
pyautogui.press("a")
pyautogui.press("r")
pyautogui.press(" ")
pyautogui.press("v")
pyautogui.press("i")
pyautogui.press("r")
pyautogui.press("u")
pyautogui.press("s")
time.sleep(3)
webbrowser. open_new_tab("https://fakeupdate.net/win10ue/")
pyautogui.press("Fn")
pyautogui.press("F11")
